### ISSUE TITLE
Brew installation broken

### ISSUE THREAD

**Issue by jonas-wanninger** [slalombuild/fusion#9]
### Describe the bug

I tried to install fusion via Homebrew and got the error message listed under current behavior.

### Expected Behavior

Executing `brew tap SlalomBuild/fusion` works.

### Current Behavior

```
brew tap SlalomBuild/fusion
==> Tapping slalombuild/fusion
Cloning into '/opt/homebrew/Library/Taps/slalombuild/homebrew-fusion'...
remote: Repository not found.
fatal: repository 'https://github.com/SlalomBuild/homebrew-fusion/' not found
Error: Failure while executing; `git clone https://github.com/SlalomBuild/homebrew-fusion 
/opt/homebrew/Library/Taps/slalombuild/homebrew-fusion --origin=origin --template=` exited with 128.
```

### Reproduction Steps

`brew tap SlalomBuild/fusion`

### Possible Solution

Adding the tap with a specific URL works though. 

`brew tap SlalomBuild/fusion https://github.com/slalombuild/fusion`

### Fusion version used (run `fusion --version` if you're unsure)

Not able to install

### Environment details (Version of Go (`go version`) if Fusion was installed via `go install`? OS name and version, etc.)

Not able to Install

**Comment by brittonhayes** [comment]
Hey @jonas-wanninger! Thanks so much for putting an issue in to let us know.

I've done some housekeeping and pushed a new release with some housekeeping fixes as well as a change to the README documentation recommending that users run the following to install fusion on OSX.

```shell
brew tap SlalomBuild/fusion https://github.com/slalombuild/fusion
brew install fusion
```
